# Generated by Django 4.2.1 on 2023-05-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Ingrese una fecha para agendar')),
                ('horario', models.CharField(choices=[('1', '09:00 a 10:00'), ('2', '10:00 a 11:00'), ('3', '11:00 a 12:00'), ('4', '12:00 a 13:00'), ('5', '13:00 a 14:00')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField(null=True)),
                ('cellNumber', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('rut', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino'), ('3', 'Prefiero no decirlo')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_clinica.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Peluquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_clinica.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('1', 'Hembra'), ('2', 'Hembra Castrada'), ('3', 'Macho'), ('4', 'Macho Castrado')], max_length=50)),
                ('fech_naci', models.DateField()),
                ('microchip', models.IntegerField()),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.cliente')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.especie')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.raza')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_clinica.genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.agenda')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_clinica.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_clinica.categoria'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='peluquera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='app_clinica.peluquera'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='app_clinica.veterinario'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('horario', 'dia')},
        ),
    ]
