# Generated by Django 4.2.1 on 2023-05-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamiento',
            name='hora',
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
