# Generated by Django 4.2.1 on 2023-05-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0002_remove_agendamiento_hora_alter_agendamiento_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamiento',
            name='fecha',
        ),
    ]
