# Generated by Django 4.2.1 on 2023-05-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0003_remove_agendamiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='fecha',
            field=models.DateTimeField(default=None),
        ),
    ]
