# Generated by Django 4.2.1 on 2023-05-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0003_alter_agendamiento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_clinica.mascota'),
        ),
    ]
