# Generated by Django 4.2.1 on 2023-05-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0004_agendamiento_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.mascota'),
        ),
    ]
