# Generated by Django 4.2.1 on 2023-05-12 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0004_agendamiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='peluquera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_clinica.peluquera'),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
