# Generated by Django 4.2.1 on 2023-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0005_alter_agendamiento_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
