# Generated by Django 4.2.1 on 2023-05-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0006_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamiento',
            name='peluquera',
        ),
        migrations.RemoveField(
            model_name='agendamiento',
            name='veterinario',
        ),
    ]
