# Generated by Django 4.2.1 on 2023-05-23 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0006_alter_agendamiento_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Ingrese una fecha para agendar')),
                ('horario', models.CharField(choices=[('1', '09:00 a 10:00'), ('2', '10:00 a 11:00'), ('3', '11:00 a 12:00'), ('4', '12:00 a 13:00'), ('5', '13:00 a 14:00')], max_length=10)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_clinica.categoria')),
                ('peluquera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='app_clinica.peluquera')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='app_clinica.veterinario')),
            ],
            options={
                'unique_together': {('horario', 'dia')},
            },
        ),
    ]
