# Generated by Django 4.2.1 on 2023-05-31 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_clinica', '0006_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='mascota',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='agendamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_clinica.agendamiento'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
