# Generated by Django 4.2.1 on 2023-05-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0007_remove_diagnostico_mascota_diagnostico_agendamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='agendamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.agendamiento'),
        ),
    ]
