# Generated by Django 4.2.1 on 2023-05-23 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0008_agendamiento_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.agenda'),
        ),
    ]
