# Generated by Django 4.2.1 on 2023-05-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0009_alter_agendamiento_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamiento',
            name='fecha',
        ),
    ]
