# Generated by Django 4.2 on 2023-05-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
