# Generated by Django 4.2.1 on 2023-05-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0004_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_tienda.marca'),
        ),
    ]
