# Generated by Django 4.2.2 on 2023-06-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0007_orden_orden_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orden_details',
            new_name='Orden_detail',
        ),
    ]
